apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ws-observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

  alerts.yml: |
    groups:
      - name: infra
        rules:
          - alert: PrometheusTargetDown
            expr: up == 0
            for: 2m
            labels:
              severity: page
            annotations:
              summary: "Prometheus target down (job={{ $labels.job }}, instance={{ $labels.instance }})"
