apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ws-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.1.0
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-password
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: traceqlEditor
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-data
        - name: provisioning
          configMap:
            name: grafana-provisioning
